"""add size classification to pokemon table

Revision ID: 0c8004ce180d
Revises: f82613162d8f
Create Date: 2026-03-18 14:33:47.500688
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8004ce180d'
down_revision: Union[str, None] = 'f82613162d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', name='size').create(op.get_bind())
    op.add_column('pokemon', sa.Column('size', sa.Enum('XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'size')
    sa.Enum(name='size').drop(op.get_bind())
    # ### end Alembic commands ###
