"""add species and pokemon tables

Revision ID: 5759ea1ac55e
Revises: 
Create Date: 2026-03-14 17:42:40.573677
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5759ea1ac55e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_stamina', sa.Integer(), nullable=False),
    sa.Column('type1', sa.Enum('BUG', 'DARK', 'DRAGON', 'ELECTRIC', 'FAIRY', 'FIGHTING', 'FIRE', 'FLYING', 'GHOST', 'GRASS', 'GROUND', 'ICE', 'NORMAL', 'POISON', 'PSYCHIC', 'ROCK', 'STEEL', 'WATER', name='pokemontype'), nullable=False),
    sa.Column('type2', sa.Enum('BUG', 'DARK', 'DRAGON', 'ELECTRIC', 'FAIRY', 'FIGHTING', 'FIRE', 'FLYING', 'GHOST', 'GRASS', 'GROUND', 'ICE', 'NORMAL', 'POISON', 'PSYCHIC', 'ROCK', 'STEEL', 'WATER', name='pokemontype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_species_dex_number'), 'species', ['dex_number'], unique=True)
    op.create_table('pokemon',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('attack_iv', sa.Integer(), nullable=False),
    sa.Column('defense_iv', sa.Integer(), nullable=False),
    sa.Column('stamina_iv', sa.Integer(), nullable=False),
    sa.Column('level', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('shadow_status', sa.Enum('NORMAL', 'SHADOW', 'PURIFIED', name='shadowstatus'), nullable=False),
    sa.Column('nickname', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_species_id'), 'pokemon', ['species_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_species_id'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_species_dex_number'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
