"""add height, weight, catch date to pokemon

Revision ID: 741c87258a2d
Revises: f885fef8989c
Create Date: 2026-04-23 14:56:10.780902
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741c87258a2d'
down_revision: Union[str, None] = 'f885fef8989c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pokemon', sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('pokemon', sa.Column('catch_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'catch_date')
    op.drop_column('pokemon', 'weight')
    op.drop_column('pokemon', 'height')
    # ### end Alembic commands ###
