"""add lucky, best buddy, shiny, and gender to pokemon table

Revision ID: f82613162d8f
Revises: 5759ea1ac55e
Create Date: 2026-03-18 14:14:06.558489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82613162d8f'
down_revision: Union[str, None] = '5759ea1ac55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NONE', 'ACHIEVED', 'ACTIVE', name='bestbuddystatus').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'GENDERLESS', name='gender').create(op.get_bind())
    op.add_column('pokemon', sa.Column('lucky', sa.Boolean(), nullable=False))
    op.add_column('pokemon', sa.Column('best_buddy', sa.Enum('NONE', 'ACHIEVED', 'ACTIVE', name='bestbuddystatus'), nullable=False))
    op.add_column('pokemon', sa.Column('shiny', sa.Boolean(), nullable=False))
    op.add_column('pokemon', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'GENDERLESS', name='gender'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'gender')
    op.drop_column('pokemon', 'shiny')
    op.drop_column('pokemon', 'best_buddy')
    op.drop_column('pokemon', 'lucky')
    sa.Enum(name='bestbuddystatus').drop(op.get_bind())
    sa.Enum(name='gender').drop(op.get_bind())
    # ### end Alembic commands ###
