"""add form column to species table

Revision ID: f885fef8989c
Revises: 0c8004ce180d
Create Date: 2026-03-25 17:15:43.269825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f885fef8989c'
down_revision: Union[str, None] = '0c8004ce180d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('form', sa.String(length=30), nullable=False))
    op.drop_constraint(op.f('species_name_key'), 'species', type_='unique')
    op.drop_index(op.f('ix_species_dex_number'), table_name='species')
    op.create_index(op.f('ix_species_dex_number'), 'species', ['dex_number'], unique=False)
    op.create_unique_constraint(None, 'species', ['dex_number', 'form'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='unique')
    op.drop_index(op.f('ix_species_dex_number'), table_name='species')
    op.create_index(op.f('ix_species_dex_number'), 'species', ['dex_number'], unique=True)
    op.create_unique_constraint(op.f('species_name_key'), 'species', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('species', 'form')
    # ### end Alembic commands ###
